- platform: GitHub
  username: soinkleined
  url: https://github.com/soinkleined
  icon: fa-brands fa-github
- platform: LinkedIn
  username: 
  url: https://www.linkedin.com/in/davidjklein/ 
  icon: fa-brands fa-linkedin

# --- Commented examples for future use ---
#- platform: Mastodon
#  username: 
#  url: 
#  icon: fa-brands fa-mastodon
#- platform: Bluesky
#  username: 
#  url: 
#  icon: fa-brands fa-bluesky
#- platform: Twitter
#  username: 
#  url: 
#  icon: fa-brands fa-twitter
# - platform: Instagram
#   username: 
#   url: 
#   icon: fa-brands fa-instagram
# - platform: YouTube
#   username: 
#   url: 
#   icon: fa-brands fa-youtube
# - platform: Facebook
#   username: 
#   url: 
#   icon: fa-brands fa-facebook
# - platform: Stack Overflow
#   username: 
#   url: 
#   icon: fa-brands fa-stack-overflow
