- platform: GitHub
  username: soinkleined
  url: https://github.com/soinkleined
  icon: fa-brands fa-github
- platform: LinkedIn
  username: 
  url: 
  icon: fa-brands fa-linkedin
- platform: Mastodon
  username: 
  url: 
  icon: fa-brands fa-mastodon
- platform: Bluesky
  username: 
  url: 
  icon: fa-brands fa-bluesky
- platform: Twitter
  username: 
  url: 
  icon: fa-brands fa-twitter
